module.exports = {
  plugins: ["stylelint-scss", "stylelint-order"],
  customSyntax: "postcss-scss",
  rules: {
    "order/properties-alphabetical-order": true,
    "font-family-name-quotes": "always-unless-keyword",
    "font-weight-notation": "numeric",
    "function-url-quotes": "always",
    "value-list-comma-newline-before": "never-multi-line",
    "declaration-block-semicolon-newline-before": "never-multi-line",
    "block-closing-brace-space-after": "always-single-line",
    "selector-attribute-quotes": "always",
    "rule-empty-line-before": [
      "always-multi-line",
      {
        ignore: ["after-comment"],
      },
    ],
    "media-feature-colon-space-after": "always",
    "media-feature-colon-space-before": "never",
    "media-feature-name-case": "lower",
    "media-feature-parentheses-space-inside": "never",
    "media-feature-range-operator-space-after": "always",
    "media-feature-range-operator-space-before": "always",
    "media-query-list-comma-newline-after": "always-multi-line",
    "media-query-list-comma-newline-before": "never-multi-line",
    "media-query-list-comma-space-after": "always-single-line",
    "media-query-list-comma-space-before": "never",
    "at-rule-empty-line-before": [
      "always",
      {
        except: ["first-nested"],
        ignore: ["after-comment", "blockless-after-same-name-blockless"],
      },
    ],
    "at-rule-name-case": "lower",
    "at-rule-name-space-after": "always-single-line",
    "at-rule-semicolon-newline-after": "always",
    "at-rule-semicolon-space-before": "never",
    "comment-empty-line-before": [
      "always",
      {
        except: ["first-nested"],
        ignore: ["stylelint-commands"],
      },
    ],
    "comment-whitespace-inside": "always",
    indentation: 2,
    linebreaks: "unix",
    "max-empty-lines": 1,
    "max-line-length": 120,
    "no-eol-whitespace": true,
    "no-missing-end-of-source-newline": true,
    "no-empty-first-line": true,
    "color-hex-case": "upper",
  },
};
