#!/usr/bin/env sh

# https://gist.github.com/rokobuljan/9b431fa1fdc438fca231b99dee2c7f3d

. "$(dirname -- "$0")/_/husky.sh"

SRC_PATH="src/ sources-default/ sources-redesign/ sources-trudvsem"
DIST_PATH="./lib ./assets"

SCRIPT_NAME=$(basename -- "$0");
CHANGED=`git diff --exit-code --cached HEAD $SRC_PATH`

# STYLES
tb=$(tput bold)
c0=$(tput sgr0)    # reset
c1=$(tput setaf 1) # red
c2=$(tput setaf 2) # green
c3=$(tput setaf 3) # yellow
c4=$(tput setaf 4) # blue
c5=$(tput setaf 5) # purple
c6=$(tput setaf 6) # cyan
c7=$(tput setaf 7) # white

if [ -z "$CHANGED" ]; then
    printf "${SCRIPT_NAME}:\n\t${c2}No changes to $SRC_PATH${c0}\n\tSkipping production build process.\n\n"
    exit 0
else
    # there are changes
    printf "${SCRIPT_NAME}:\n\t${c1}Changes detected in ${SRC_PATH}${c0}\n\tBuilding distribution files in ${DIST_PATH}\n\tAdding files to the current commit.${c0}\n\n"
    npm run build:all && git add ${DIST_PATH} && exit
fi
npm run build:all

git add ./lib ./assets